AllCops:
  Include:
    - '**/Rakefile'
    - lib/**/*
  Exclude:
    - Gemfile

Lint/DuplicateMethods:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Naming/PredicateName:
  NamePrefix:
    - is_
    - have_

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false
