AllCops:
  Include:
    - '**/Rakefile'
    - lib/**/*
  Exclude:
    - Gemfile

Documentation:
  Enabled: false

LineLength:
  Enabled: false

Naming/PredicateName:
  NamePrefix:
    - is_
    - have_

Style/MissingRespondToMissing:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false
